version: "3.9"

services:
  web:
    build:
      context: ./magnus-talent-agent
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    env_file: .env
    depends_on: [redis]

  worker:
    build:
      context: .
      dockerfile: magnus-talent-worker/Dockerfile
    env_file: .env
    depends_on: [redis]

  redis:
    image: redis:7-alpine
